// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# The Assets API exposes fixed asset related functions of the Xero Accounting application and can be used for a variety of purposes such as creating assets, retrieving asset valuations etc.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.xero.com/assets.xro/1.0") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # searches fixed asset
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - search results matching criteria 
    remote isolated function listAssets(ListAssetsHeaders headers, *ListAssetsQueries queries) returns Assets|error {
        string resourcePath = string `/Assets`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # adds a fixed asset
    #
    # + headers - Headers to be sent with the request 
    # + payload - Fixed asset you are creating 
    # + return - return single object - create new asset 
    remote isolated function createAsset(CreateAssetHeaders headers, Asset payload) returns Asset|error {
        string resourcePath = string `/Assets`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieves fixed asset by id
    #
    # + id - fixed asset id for single object
    # + headers - Headers to be sent with the request 
    # + return - search results matching criteria 
    remote isolated function getAsset(string id, GetAssetHeaders headers) returns Asset|error {
        string resourcePath = string `/Assets/${getEncodedUri(id)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # searches fixed asset types
    #
    # + headers - Headers to be sent with the request 
    # + return - search results matching criteria 
    remote isolated function listAssetTypes(ListAssetTypesHeaders headers) returns AssetType[]|error {
        string resourcePath = string `/AssetTypes`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # adds a fixed asset type
    #
    # + headers - Headers to be sent with the request 
    # + payload - Asset type to add 
    # + return - results single object -  created fixed type 
    remote isolated function createAssetType(CreateAssetTypeHeaders headers, AssetType payload) returns AssetType|error {
        string resourcePath = string `/AssetTypes`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # searches fixed asset settings
    #
    # + headers - Headers to be sent with the request 
    # + return - search results matching criteria 
    remote isolated function getSettings(GetSettingsHeaders headers) returns Setting|error {
        string resourcePath = string `/Settings`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }
}
