// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

public type BookDepreciationSetting record {
    # The method of depreciation applied to this asset. See Depreciation Methods
    "NoDepreciation"|"StraightLine"|"DiminishingValue100"|"DiminishingValue150"|"DiminishingValue200"|"FullDepreciation" depreciationMethod?;
    # The method of averaging applied to this asset. See Averaging Methods
    "FullMonth"|"ActualDays" averagingMethod?;
    # The rate of depreciation (e.g. 0.05)
    decimal depreciationRate?;
    # Effective life of the asset in years (e.g. 5)
    int effectiveLifeYears?;
    # See Depreciation Calculation Methods
    "Rate"|"Life"|"None" depreciationCalculationMethod?;
    # Unique Xero identifier for the depreciable object
    string depreciableObjectId?;
    # The type of asset object
    string depreciableObjectType?;
    # Unique Xero identifier for the effective date change
    string bookEffectiveDateOfChangeId?;
};

# Represents the Headers record for the operation: createAssetType
public type CreateAssetTypeHeaders record {
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Queries record for the operation: listAssets
public type ListAssetsQueries record {
    # ASC or DESC
    "asc"|"desc" sortDirection?;
    # The number of records returned per page. By default the number of records returned is 10
    int pageSize?;
    # Requests can be ordered by AssetType, AssetName, AssetNumber, PurchaseDate and PurchasePrice. If the asset status is DISPOSED it also allows DisposalDate and DisposalPrice
    "AssetType"|"AssetName"|"AssetNumber"|"PurchaseDate"|"PurchasePrice"|"DisposalDate"|"DisposalPrice" orderBy?;
    # Results are paged. This specifies which page of the results to return. The default page is 1
    int page?;
    # A string that can be used to filter the list to only return assets containing the text. Checks it against the AssetName, AssetNumber, Description and AssetTypeName fields
    string filterBy?;
    # Required when retrieving a collection of assets. See Asset Status Codes
    AssetStatusQueryParam status;
};

# Represents the Headers record for the operation: createAsset
public type CreateAssetHeaders record {
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

public type BookDepreciationDetail record {
    # When an asset is disposed, this will be the sell price minus the purchase price if a profit was made.
    decimal currentCapitalGain?;
    # When an asset is disposed, this will be the lowest one of sell price or purchase price, minus the current book value.
    decimal currentGainLoss?;
    # YYYY-MM-DD
    string depreciationStartDate?;
    # The value of the asset you want to depreciate, if this is less than the cost of the asset.
    decimal costLimit?;
    # The value of the asset remaining when you've fully depreciated it.
    decimal residualValue?;
    # All depreciation prior to the current financial year.
    decimal priorAccumDepreciationAmount?;
    # All depreciation occurring in the current financial year.
    decimal currentAccumDepreciationAmount?;
    # (New Zealand Orgs Only) The portion of capital gain realised from the disposal of a fixed asset that is attributable to its business use.
    decimal businessUseCapitalGain?;
    # (New Zealand Orgs Only) Represents the gain or loss from the disposal of the business use portion of a fixed asset. This value records the financial result (profit or loss) related specifically to the asset’s business use.
    decimal businessUseCurrentGainLoss?;
    # (New Zealand Orgs Only) The portion of capital gain realised from the disposal of a fixed asset that is attributable to its private (non-business) use.
    decimal privateUseCapitalGain?;
    # (New Zealand Orgs Only) Represents the gain or loss from the disposal of the private use portion of a fixed asset. This value records the financial result (profit or loss) related specifically to the asset’s private use.
    decimal privateUseCurrentGainLoss?;
    # (New Zealand Orgs Only) The Investment Boost deduction percentage.
    decimal initialDeductionPercentage?;
};

# Represents the Headers record for the operation: listAssets
public type ListAssetsHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

public type Setting record {
    # The prefix used for fixed asset numbers (“FA-” by default)
    string assetNumberPrefix?;
    # The date depreciation calculations started on registered fixed assets in Xero
    string assetStartDate?;
    # The next available sequence number
    string assetNumberSequence?;
    # Default account that gains are posted to
    string defaultGainOnDisposalAccountId?;
    # The last depreciation date
    string lastDepreciationDate?;
    # Default account that capital gains are posted to
    string defaultCapitalGainOnDisposalAccountId?;
    # Default account that losses are posted to
    string defaultLossOnDisposalAccountId?;
    # opt in for tax calculation
    boolean optInForTax?;
};

# See Asset Status Codes
public type AssetStatus "Draft"|"Registered"|"Disposed";

# Represents the Headers record for the operation: getSettings
public type GetSettingsHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: listAssetTypes
public type ListAssetTypesHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# See Asset Status Codes
public type AssetStatusQueryParam "DRAFT"|"REGISTERED"|"DISPOSED";

public type Pagination record {
    int page?;
    int pageSize?;
    int pageCount?;
    int itemCount?;
};

public type AssetType record {
    # Xero generated unique identifier for asset types
    string assetTypeId?;
    BookDepreciationSetting bookDepreciationSetting;
    # The name of the asset type
    string assetTypeName;
    # The expense account for the depreciation of fixed assets of this type
    string depreciationExpenseAccountId?;
    # The asset account for fixed assets of this type
    string fixedAssetAccountId?;
    # The account for accumulated depreciation of fixed assets of this type
    string accumulatedDepreciationAccountId?;
    # All asset types that have accumulated depreciation for any assets that use them are deemed ‘locked’ and cannot be removed
    int locks?;
};

public type Assets record {
    Pagination pagination?;
    Asset[] items?;
};

public type Asset record {
    # The date the asset was purchased YYYY-MM-DD
    string purchaseDate?;
    # The asset's serial number
    string serialNumber?;
    # The Xero-generated Id for the asset type
    string assetTypeId?;
    # The purchase price of the asset
    decimal purchasePrice?;
    # Boolean to indicate whether delete is enabled
    boolean isDeleteEnabledForDate?;
    # Must be unique
    string assetNumber?;
    BookDepreciationSetting bookDepreciationSetting?;
    # The date the asset’s warranty expires (if needed) YYYY-MM-DD
    string warrantyExpiryDate?;
    # The Xero-generated Id for the asset
    string assetId?;
    # The accounting value of the asset
    decimal accountingBookValue?;
    # The date the asset was disposed
    string disposalDate?;
    # Boolean to indicate whether depreciation can be rolled back for this asset individually. This is true if it doesn't have 'legacy' journal entries and if there is no lock period that would prevent this asset from rolling back
    boolean canRollback?;
    # The name of the asset
    string assetName;
    # The price the asset was disposed at
    decimal disposalPrice?;
    # See Asset Status Codes
    AssetStatus assetStatus?;
    BookDepreciationDetail bookDepreciationDetail?;
};

# OAuth2 Refresh Token Grant Configs
public type OAuth2RefreshTokenGrantConfig record {|
    *http:OAuth2RefreshTokenGrantConfig;
    # Refresh URL
    string refreshUrl = "https://identity.xero.com/connect/token";
|};

# Represents the Headers record for the operation: getAsset
public type GetAssetHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig|OAuth2RefreshTokenGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
